<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="jest tests" tests="76" failures="2" errors="0" time="3.054">
  <testsuite name="HoldCall Action" errors="0" failures="0" skipped="0" timestamp="2023-02-08T07:01:39" time="0.968" tests="4">
    <testcase classname="HoldCall Action adds beforeRejectTask listener" name="HoldCall Action adds beforeRejectTask listener" time="0.002">
    </testcase>
    <testcase classname="HoldCall Action should not call InternalCallService.rejectInternalTask as it is not an internal call" name="HoldCall Action should not call InternalCallService.rejectInternalTask as it is not an internal call" time="0">
    </testcase>
    <testcase classname="HoldCall Action should call InternalCallService.rejectInternalTask with correct parameters" name="HoldCall Action should call InternalCallService.rejectInternalTask with correct parameters" time="0.001">
    </testcase>
    <testcase classname="HoldCall Action should not call InternalCallService.rejectInternalTask with incorrect participantType" name="HoldCall Action should not call InternalCallService.rejectInternalTask with incorrect participantType" time="0.001">
    </testcase>
  </testsuite>
  <testsuite name="holdParticipant tests from ConferenceParticipant" errors="0" failures="0" skipped="0" timestamp="2023-02-08T07:01:39" time="1.064" tests="11">
    <testcase classname="holdParticipant tests from ConferenceParticipant holdParticipant returns success response" name="holdParticipant tests from ConferenceParticipant holdParticipant returns success response" time="0.01">
    </testcase>
    <testcase classname="holdParticipant tests from ConferenceParticipant holdParticipant throws invalid parameters object passed" name="holdParticipant tests from ConferenceParticipant holdParticipant throws invalid parameters object passed" time="0.001">
    </testcase>
    <testcase classname="holdParticipant tests from ConferenceParticipant holdParticipant throws invalid parameters object passed" name="holdParticipant tests from ConferenceParticipant holdParticipant throws invalid parameters object passed" time="0">
    </testcase>
    <testcase classname="holdParticipant tests from ConferenceParticipant holdParticipant throws invalid parameters object passed" name="holdParticipant tests from ConferenceParticipant holdParticipant throws invalid parameters object passed" time="0">
    </testcase>
    <testcase classname="holdParticipant tests from ConferenceParticipant holdParticipant throws invalid parameters object passed" name="holdParticipant tests from ConferenceParticipant holdParticipant throws invalid parameters object passed" time="0">
    </testcase>
    <testcase classname="updateParticipant tests from ConferenceParticipant updateParticipant returns success response" name="updateParticipant tests from ConferenceParticipant updateParticipant returns success response" time="0">
    </testcase>
    <testcase classname="updateParticipant tests from ConferenceParticipant updateParticipant throws invalid parameters object passed" name="updateParticipant tests from ConferenceParticipant updateParticipant throws invalid parameters object passed" time="0">
    </testcase>
    <testcase classname="updateParticipant tests from ConferenceParticipant updateParticipant throws invalid parameters object passed" name="updateParticipant tests from ConferenceParticipant updateParticipant throws invalid parameters object passed" time="0">
    </testcase>
    <testcase classname="updateParticipant tests from ConferenceParticipant updateParticipant throws invalid parameters object passed" name="updateParticipant tests from ConferenceParticipant updateParticipant throws invalid parameters object passed" time="0.001">
    </testcase>
    <testcase classname="updateParticipant tests from ConferenceParticipant updateParticipant throws invalid parameters object passed" name="updateParticipant tests from ConferenceParticipant updateParticipant throws invalid parameters object passed" time="0">
    </testcase>
    <testcase classname="fetchByTask tests from ConferenceParticipant fetchByTask is called successfully" name="fetchByTask tests from ConferenceParticipant fetchByTask is called successfully" time="0">
    </testcase>
  </testsuite>
  <testsuite name="a completed conference" errors="0" failures="0" skipped="0" timestamp="2023-02-08T07:01:39" time="1.106" tests="2">
    <testcase classname="a completed conference returns a VoiceResponse" name="a completed conference returns a VoiceResponse" time="0.059">
    </testcase>
    <testcase classname="a completed conference returns a twiml call" name="a completed conference returns a twiml call" time="0.001">
    </testcase>
  </testsuite>
  <testsuite name="taskrouter.createTask" errors="0" failures="0" skipped="0" timestamp="2023-02-08T07:01:39" time="1.146" tests="11">
    <testcase classname="taskrouter.createTask createTask gives success" name="taskrouter.createTask createTask gives success" time="0.023">
    </testcase>
    <testcase classname="taskrouter.createTask createTask gives error due to invalid taskChannel" name="taskrouter.createTask createTask gives error due to invalid taskChannel" time="0">
    </testcase>
    <testcase classname="taskrouter.createTask createTask gives error due to invalid attributes" name="taskrouter.createTask createTask gives error due to invalid attributes" time="0.001">
    </testcase>
    <testcase classname="taskrouter.fetchTask fetchTask gives success" name="taskrouter.fetchTask fetchTask gives success" time="0">
    </testcase>
    <testcase classname="taskrouter.fetchTask fetchTask gives error due to invalid attempts" name="taskrouter.fetchTask fetchTask gives error due to invalid attempts" time="0.001">
    </testcase>
    <testcase classname="taskrouter.fetchTask fetchTask gives error due to invalid taskSid" name="taskrouter.fetchTask fetchTask gives error due to invalid taskSid" time="0">
    </testcase>
    <testcase classname="taskrouter.fetchTask fetchTask gives error due to invalid context" name="taskrouter.fetchTask fetchTask gives error due to invalid context" time="0">
    </testcase>
    <testcase classname="taskrouter.updateTaskAttributes updateTaskAttributes gives success" name="taskrouter.updateTaskAttributes updateTaskAttributes gives success" time="0.002">
    </testcase>
    <testcase classname="taskrouter.updateTaskAttributes updateTaskAttributes gives error due to invalid attempts" name="taskrouter.updateTaskAttributes updateTaskAttributes gives error due to invalid attempts" time="0.001">
    </testcase>
    <testcase classname="taskrouter.updateTaskAttributes updateTaskAttributes gives error due to invalid taskSid" name="taskrouter.updateTaskAttributes updateTaskAttributes gives error due to invalid taskSid" time="0">
    </testcase>
    <testcase classname="taskrouter.updateTaskAttributes updateTaskAttributes gives error due to invalid attributesUpdate" name="taskrouter.updateTaskAttributes updateTaskAttributes gives error due to invalid attributesUpdate" time="0">
    </testcase>
  </testsuite>
  <testsuite name="CallCanvas" errors="0" failures="0" skipped="0" timestamp="2023-02-08T07:01:39" time="1.269" tests="1">
    <testcase classname="CallCanvas adds InternalDialpad to call canvas" name="CallCanvas adds InternalDialpad to call canvas" time="0.001">
    </testcase>
  </testsuite>
  <testsuite name="HoldCall Action" errors="0" failures="0" skipped="0" timestamp="2023-02-08T07:01:40" time="0.331" tests="4">
    <testcase classname="HoldCall Action adds beforeHoldParticipant listener" name="HoldCall Action adds beforeHoldParticipant listener" time="0.002">
    </testcase>
    <testcase classname="HoldCall Action should not call InternalCallService.holdParticipant as it is not an internal call" name="HoldCall Action should not call InternalCallService.holdParticipant as it is not an internal call" time="0.001">
    </testcase>
    <testcase classname="HoldCall Action should call InternalCallService.holdParticipant with correct parameters" name="HoldCall Action should call InternalCallService.holdParticipant with correct parameters" time="0.001">
    </testcase>
    <testcase classname="HoldCall Action should not call InternalCallService.holdParticipant with incorrect participantType" name="HoldCall Action should not call InternalCallService.holdParticipant with incorrect participantType" time="0">
    </testcase>
  </testsuite>
  <testsuite name="Remove Participant" errors="0" failures="0" skipped="0" timestamp="2023-02-08T07:01:40" time="0.417" tests="1">
    <testcase classname="Remove Participant CleanUpTask is called successfully " name="Remove Participant CleanUpTask is called successfully " time="0.009">
    </testcase>
  </testsuite>
  <testsuite name="utils/common/ApiService" errors="0" failures="0" skipped="0" timestamp="2023-02-08T07:01:39" time="1.431" tests="5">
    <testcase classname="utils/common/ApiService should provide access to the Flex Manager instance" name="utils/common/ApiService should provide access to the Flex Manager instance" time="0.001">
    </testcase>
    <testcase classname="utils/common/ApiService should build encoded params into a string to use as the body for serverless reqeusts" name="utils/common/ApiService should build encoded params into a string to use as the body for serverless reqeusts" time="0">
    </testcase>
    <testcase classname="utils/common/ApiService fetchJsonWithReject should return json response" name="utils/common/ApiService fetchJsonWithReject should return json response" time="0.002">
    </testcase>
    <testcase classname="utils/common/ApiService fetchJsonWithReject should throw error" name="utils/common/ApiService fetchJsonWithReject should throw error" time="0.001">
    </testcase>
    <testcase classname="utils/common/ApiService fetchJsonWithReject should retry on error" name="utils/common/ApiService fetchJsonWithReject should retry on error" time="0.402">
    </testcase>
  </testsuite>
  <testsuite name="a completed conference" errors="0" failures="0" skipped="0" timestamp="2023-02-08T07:01:41" time="0.288" tests="2">
    <testcase classname="a completed conference returns a VoiceResponse" name="a completed conference returns a VoiceResponse" time="0.059">
    </testcase>
    <testcase classname="a completed conference returns a twiml call" name="a completed conference returns a twiml call" time="0.001">
    </testcase>
  </testsuite>
  <testsuite name="UnholdParticipant Action" errors="0" failures="0" skipped="0" timestamp="2023-02-08T07:01:41" time="0.192" tests="4">
    <testcase classname="UnholdParticipant Action adds beforeUnholdParticipant listener" name="UnholdParticipant Action adds beforeUnholdParticipant listener" time="0.002">
    </testcase>
    <testcase classname="UnholdParticipant Action should not call InternalCallService.unholdParticipant as it is not an internal call" name="UnholdParticipant Action should not call InternalCallService.unholdParticipant as it is not an internal call" time="0.001">
    </testcase>
    <testcase classname="UnholdParticipant Action should call InternalCallService.unholdParticipant with correct parameters" name="UnholdParticipant Action should call InternalCallService.unholdParticipant with correct parameters" time="0">
    </testcase>
    <testcase classname="UnholdParticipant Action should not call InternalCallService.unholdParticipant with incorrect participantType" name="UnholdParticipant Action should not call InternalCallService.unholdParticipant with incorrect participantType" time="0">
    </testcase>
  </testsuite>
  <testsuite name="CallCanvas" errors="0" failures="1" skipped="0" timestamp="2023-02-08T07:01:41" time="0.401" tests="1">
    <testcase classname="CallCanvas removes directory from call canvas" name="CallCanvas removes directory from call canvas" time="0.003">
      <failure>Error: expect(jest.fn()).toHaveBeenCalledWith(...expected)

- Expected
+ Received

  &quot;directory&quot;,
  Object {
-   &quot;if&quot;: true,
+   &quot;if&quot;: [Function isInternalCall],
  },

Number of calls: 1
    at Object.&lt;anonymous&gt; (/Users/hsingla/code/workspace/flex-internal-call-plugin/src/flex-hooks/components/__tests__/CallCanvasActions.test.tsx:12:27)
    at Object.asyncJestTest (/Users/hsingla/code/workspace/flex-internal-call-plugin/node_modules/jest-jasmine2/build/jasmineAsyncInstall.js:106:37)
    at /Users/hsingla/code/workspace/flex-internal-call-plugin/node_modules/jest-jasmine2/build/queueRunner.js:45:12
    at new Promise (&lt;anonymous&gt;)
    at mapper (/Users/hsingla/code/workspace/flex-internal-call-plugin/node_modules/jest-jasmine2/build/queueRunner.js:28:19)
    at /Users/hsingla/code/workspace/flex-internal-call-plugin/node_modules/jest-jasmine2/build/queueRunner.js:75:41
    at processTicksAndRejections (node:internal/process/task_queues:96:5)</failure>
    </testcase>
  </testsuite>
  <testsuite name="InternalCall notification" errors="0" failures="0" skipped="0" timestamp="2023-02-08T07:01:41" time="0.196" tests="2">
    <testcase classname="InternalCall notification adds beforeAddNotification listener" name="InternalCall notification adds beforeAddNotification listener" time="0.001">
    </testcase>
    <testcase classname="InternalCall notification should call beforeAddNotification listener" name="InternalCall notification should call beforeAddNotification listener" time="0.001">
    </testcase>
  </testsuite>
  <testsuite name="Prepare Flex Function" errors="0" failures="0" skipped="0" timestamp="2023-02-08T07:01:41" time="0.217" tests="4">
    <testcase classname="Prepare Flex Function prepareFlexFunction is called successfully " name="Prepare Flex Function prepareFlexFunction is called successfully " time="0.006">
    </testcase>
    <testcase classname="Prepare Function prepareFlexFunction is called successfully " name="Prepare Function prepareFlexFunction is called successfully " time="0.001">
    </testcase>
    <testcase classname="Prepare Function prepareFlexFunction returns error 400" name="Prepare Function prepareFlexFunction returns error 400" time="0">
    </testcase>
    <testcase classname="Prepare Function prepareFlexFunction error handler" name="Prepare Function prepareFlexFunction error handler" time="0">
    </testcase>
  </testsuite>
  <testsuite name="HoldCall Action" errors="0" failures="0" skipped="0" timestamp="2023-02-08T07:01:41" time="0.19" tests="4">
    <testcase classname="HoldCall Action adds beforeAcceptTask listener" name="HoldCall Action adds beforeAcceptTask listener" time="0.002">
    </testcase>
    <testcase classname="HoldCall Action should call InternalCallService.acceptInternalTask with correct parameters" name="HoldCall Action should call InternalCallService.acceptInternalTask with correct parameters" time="0.001">
    </testcase>
    <testcase classname="HoldCall Action should not call InternalCallService.acceptInternalTask as it is not an internal call" name="HoldCall Action should not call InternalCallService.acceptInternalTask as it is not an internal call" time="0">
    </testcase>
    <testcase classname="HoldCall Action should not call InternalCallService.acceptInternalTask with incorrect participantType" name="HoldCall Action should not call InternalCallService.acceptInternalTask with incorrect participantType" time="0">
    </testcase>
  </testsuite>
  <testsuite name="holdParticipant" errors="0" failures="0" skipped="0" timestamp="2023-02-08T07:01:41" time="0.25" tests="8">
    <testcase classname="holdParticipant adds participant to the conference successfully" name="holdParticipant adds participant to the conference successfully" time="0.003">
    </testcase>
    <testcase classname="holdParticipant throws error when trying to add a participant to the conference" name="holdParticipant throws error when trying to add a participant to the conference" time="0">
    </testcase>
    <testcase classname="unholdParticipant adds participant to the conference successfully" name="unholdParticipant adds participant to the conference successfully" time="0">
    </testcase>
    <testcase classname="unholdParticipant throws error when trying to add a participant to the conference" name="unholdParticipant throws error when trying to add a participant to the conference" time="0">
    </testcase>
    <testcase classname="rejectInternalTask rejects an internal task successfully" name="rejectInternalTask rejects an internal task successfully" time="0.001">
    </testcase>
    <testcase classname="rejectInternalTask throws error when trying to add a participant to the conference" name="rejectInternalTask throws error when trying to add a participant to the conference" time="0.003">
    </testcase>
    <testcase classname="acceptInternalTask rejects an internal task with conference successfully" name="acceptInternalTask rejects an internal task with conference successfully" time="0.001">
    </testcase>
    <testcase classname="acceptInternalTask rejects an internal task without conference successfully" name="acceptInternalTask rejects an internal task without conference successfully" time="0">
    </testcase>
  </testsuite>
  <testsuite name="Hold Participant" errors="0" failures="0" skipped="0" timestamp="2023-02-08T07:01:41" time="0.22" tests="2">
    <testcase classname="Hold Participant holdParticipant is called successfully " name="Hold Participant holdParticipant is called successfully " time="0.008">
    </testcase>
    <testcase classname="Hold Participant holdParticipant thorws error" name="Hold Participant holdParticipant thorws error" time="0.001">
    </testcase>
  </testsuite>
  <testsuite name="Retry Handler" errors="0" failures="0" skipped="0" timestamp="2023-02-08T07:01:41" time="0.178" tests="3">
    <testcase classname="Retry Handler throws invalid parameter error" name="Retry Handler throws invalid parameter error" time="0.002">
    </testcase>
    <testcase classname="Retry Handler returns failed status" name="Retry Handler returns failed status" time="0.002">
    </testcase>
    <testcase classname="Retry Handler retry callback is called" name="Retry Handler retry callback is called" time="0.004">
    </testcase>
  </testsuite>
  <testsuite name="undefined" errors="0" failures="0" skipped="0" timestamp="2023-02-08T07:01:41" time="0.122" tests="5">
    <testcase classname=" parameterValitor returns success with strings" name=" parameterValitor returns success with strings" time="0.001">
    </testcase>
    <testcase classname=" parameterValitor returns success with object" name=" parameterValitor returns success with object" time="0">
    </testcase>
    <testcase classname=" parameterValitor returns error with strings" name=" parameterValitor returns error with strings" time="0.001">
    </testcase>
    <testcase classname=" parameterValitor returns error with object" name=" parameterValitor returns error with object" time="0">
    </testcase>
    <testcase classname=" parameterValitor returns error with numerical keys" name=" parameterValitor returns error with numerical keys" time="0">
    </testcase>
  </testsuite>
  <testsuite name="plugins loaded" errors="0" failures="0" skipped="0" timestamp="2023-02-08T07:01:41" time="0.114" tests="1">
    <testcase classname="plugins loaded check plugins loaded" name="plugins loaded check plugins loaded" time="0.001">
    </testcase>
  </testsuite>
  <testsuite name="InternalDialpad" errors="0" failures="1" skipped="0" timestamp="2023-02-08T07:01:39" time="1.843" tests="1">
    <testcase classname="InternalDialpad should render correct snapshot" name="InternalDialpad should render correct snapshot" time="0.032">
      <failure>TypeError: Cannot read properties of undefined (reading &apos;map&apos;)
    at useWindowSize (/Users/hsingla/code/workspace/flex-internal-call-plugin/node_modules/@twilio-paste/utils/dist/index.js:1:54385)
    at /Users/hsingla/code/workspace/flex-internal-call-plugin/node_modules/@twilio-paste/combobox/dist/index.js:2712:42
    at renderWithHooks (/Users/hsingla/code/workspace/flex-internal-call-plugin/node_modules/react-dom/cjs/react-dom.development.js:2522:157)
    at updateForwardRef (/Users/hsingla/code/workspace/flex-internal-call-plugin/node_modules/react-dom/cjs/react-dom.development.js:2720:145)
    at beginWork (/Users/hsingla/code/workspace/flex-internal-call-plugin/node_modules/react-dom/cjs/react-dom.development.js:3105:1579)
    at HTMLUnknownElement.callCallback (/Users/hsingla/code/workspace/flex-internal-call-plugin/node_modules/react-dom/cjs/react-dom.development.js:657:119)
    at HTMLUnknownElement.callTheUserObjectsOperation (/Users/hsingla/code/workspace/flex-internal-call-plugin/node_modules/jsdom/lib/jsdom/living/generated/EventListener.js:26:30)
    at innerInvokeEventListeners (/Users/hsingla/code/workspace/flex-internal-call-plugin/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:338:25)
    at invokeEventListeners (/Users/hsingla/code/workspace/flex-internal-call-plugin/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:274:3)
    at HTMLUnknownElementImpl._dispatch (/Users/hsingla/code/workspace/flex-internal-call-plugin/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:221:9)
    at HTMLUnknownElementImpl.dispatchEvent (/Users/hsingla/code/workspace/flex-internal-call-plugin/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:94:17)
    at HTMLUnknownElement.dispatchEvent (/Users/hsingla/code/workspace/flex-internal-call-plugin/node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:231:34)
    at Object.invokeGuardedCallbackDev (/Users/hsingla/code/workspace/flex-internal-call-plugin/node_modules/react-dom/cjs/react-dom.development.js:677:45)
    at invokeGuardedCallback (/Users/hsingla/code/workspace/flex-internal-call-plugin/node_modules/react-dom/cjs/react-dom.development.js:696:126)
    at beginWork$1 (/Users/hsingla/code/workspace/flex-internal-call-plugin/node_modules/react-dom/cjs/react-dom.development.js:4040:1)
    at performUnitOfWork (/Users/hsingla/code/workspace/flex-internal-call-plugin/node_modules/react-dom/cjs/react-dom.development.js:3829:270)
    at workLoopSync (/Users/hsingla/code/workspace/flex-internal-call-plugin/node_modules/react-dom/cjs/react-dom.development.js:3822:30)
    at renderRootSync (/Users/hsingla/code/workspace/flex-internal-call-plugin/node_modules/react-dom/cjs/react-dom.development.js:3819:195)
    at performSyncWorkOnRoot (/Users/hsingla/code/workspace/flex-internal-call-plugin/node_modules/react-dom/cjs/react-dom.development.js:3749:121)
    at scheduleUpdateOnFiber (/Users/hsingla/code/workspace/flex-internal-call-plugin/node_modules/react-dom/cjs/react-dom.development.js:3630:1)
    at updateContainer (/Users/hsingla/code/workspace/flex-internal-call-plugin/node_modules/react-dom/cjs/react-dom.development.js:4229:313)
    at /Users/hsingla/code/workspace/flex-internal-call-plugin/node_modules/react-dom/cjs/react-dom.development.js:4272:29
    at unbatchedUpdates (/Users/hsingla/code/workspace/flex-internal-call-plugin/node_modules/react-dom/cjs/react-dom.development.js:3774:209)
    at legacyRenderSubtreeIntoContainer (/Users/hsingla/code/workspace/flex-internal-call-plugin/node_modules/react-dom/cjs/react-dom.development.js:4272:1)
    at Object.render (/Users/hsingla/code/workspace/flex-internal-call-plugin/node_modules/react-dom/cjs/react-dom.development.js:4274:519)
    at /Users/hsingla/code/workspace/flex-internal-call-plugin/node_modules/@testing-library/react/dist/pure.js:123:25
    at batchedUpdates$1 (/Users/hsingla/code/workspace/flex-internal-call-plugin/node_modules/react-dom/cjs/react-dom.development.js:3771:145)
    at act (/Users/hsingla/code/workspace/flex-internal-call-plugin/node_modules/react-dom/cjs/react-dom-test-utils.development.js:924:18)
    at render (/Users/hsingla/code/workspace/flex-internal-call-plugin/node_modules/@testing-library/react/dist/pure.js:119:26)
    at Object.&lt;anonymous&gt; (/Users/hsingla/code/workspace/flex-internal-call-plugin/src/components/__tests__/InternalDialpad.test.tsx:11:27)
    at Object.asyncJestTest (/Users/hsingla/code/workspace/flex-internal-call-plugin/node_modules/jest-jasmine2/build/jasmineAsyncInstall.js:106:37)
    at /Users/hsingla/code/workspace/flex-internal-call-plugin/node_modules/jest-jasmine2/build/queueRunner.js:45:12
    at new Promise (&lt;anonymous&gt;)
    at mapper (/Users/hsingla/code/workspace/flex-internal-call-plugin/node_modules/jest-jasmine2/build/queueRunner.js:28:19)
    at /Users/hsingla/code/workspace/flex-internal-call-plugin/node_modules/jest-jasmine2/build/queueRunner.js:75:41
    at processTicksAndRejections (node:internal/process/task_queues:96:5)</failure>
    </testcase>
  </testsuite>
</testsuites>